# Generated by Django 2.1.7 on 2022-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='company-1.png', upload_to='profile_images'),
        ),
    ]
