# Generated by Django 2.1.7 on 2022-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221212_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='BG_1.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default='APPENDIX.pdf', upload_to='resumes'),
        ),
    ]
