# Generated by Django 2.1.7 on 2022-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default='', upload_to='resumes'),
        ),
    ]
