# Generated by Django 2.1.7 on 2022-12-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_province'),
        ('accounts', '0008_auto_20221215_1742'),
    ]

    operations = [
    ]
