# Generated by Django 2.1.7 on 2022-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20221223_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(error_messages={'required': 'Role must be provided'}, max_length=12),
        ),
    ]
