# Generated by Django 2.1.7 on 2022-12-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_auto_20221216_1138'),
        ('jobsapp', '0007_inactivejob'),
    ]

    operations = [
    ]
