# Generated by Django 2.1.7 on 2022-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_merge_20221223_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inactivejob',
            old_name='category',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='inactivejob',
            old_name='company_name',
            new_name='skillReq',
        ),
        migrations.RemoveField(
            model_name='inactivejob',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='inactivejob',
            name='website',
        ),
        migrations.AlterField(
            model_name='inactivejob',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time')], max_length=10),
        ),
    ]
